version: '3'
services:
  spring-app:
    image: your-docker-image:tag
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your-password
      MYSQL_DATABASE: your-database
